export const Roles = [
	"Growth Marketing Expert",
	"Data Analyst",
	"Sales Development Representative (SDR)/Sales Executive",
	"Customer Support Representative",
	"Market Research Analyst",
	"Social Media Manager",
	"Project Manager",
	"Performance Marketer / Paid Ads Specialist",
	"Content Strategist / Copywriter",
	"Product Marketing / GTM Specialist",
	"Email & Automation Specialist",
	"Operations / Process Manager",
	"PR Manager",
	"Head of Growth",
	"Brand Manager",
	"Business Development Manager",
	"Key Accounts Manager",
	"Community Manager",
	"Product Manager (Growth PM)",
	"SEO Specialist",
	"Video Editor",
];

export const Skills = [
	"Sales Prospecting",
	"Lead Generation",
	"Cold Calling",
	"Cold Emailing",
	"Sales Closing",
	"Objection Handling",
	"Negotiation",
	"Pitching & Demo Delivery",
	"Pipeline Management",
	"Sales Strategy",
	"Sales Forecasting",
	"Proposal Writing",
	"Relationship Management",
	"Account Management",
	"Deal Structuring",
	"Partnership Development",
	"Partnership Management",
	"Partnership Negotiation",
	"Co-marketing Partnerships",
	"Strategic Alliances",
	"Business Development Strategy",
	"Stakeholder Management",
	"Digital Marketing",
	"Content Marketing",
	"Social Media Management",
	"Email Marketing",
	"SEO",
	"Paid Ads Management",
	"Funnel Building",
	"Conversion Rate Optimization (CRO)",
	"A/B Testing",
	"Growth Experimentation",
	"Growth Loops",
	"User Acquisition",
	"User Engagement",
	"User Retention Strategy",
	"Product-Led Growth (PLG)",
	"Product Positioning",
	"Product Messaging",
	"Value Proposition Design",
	"Go-To-Market Strategy (GTM)",
	"Competitor Analysis",
	"Customer Insights & Research",
	"Customer Onboarding",
	"Customer Training",
	"Customer Support",
	"Relationship Building",
	"Upselling",
	"Cross-selling",
	"Churn Reduction",
	"Renewal Management",
	"Customer Feedback Collection",
	"Customer Journey Mapping",
	"CRM Management",
	"Sales Process Optimization",
	"Reporting & Analytics",
	"Workflow Automation",
	"Revenue Operations",
	"HubSpot",
	"Salesforce",
	"Zoho CRM",
	"Pipedrive",
	"Apollo",
	"Outreach",
	"Communication",
	"Leadership",
	"Emotional Intelligence",
	"Critical Thinking",
	"Problem Solving",
	"Creativity",
	"Collaboration",
	"Time Management",
	"Presentation Skills",
	"Analytical Thinking",
	"Adaptability",
	"Decision Making",
	"Project Management",
];

export const preferredIndustries = [
	"A/B Testing",
	"Accounting & Audit",
	"Adaptability",
	"Agriculture & Agribusiness",
	"Agritech",
	"AI & Data Science",
	"Analytical Thinking",
	"Apollo",
	"Art & Culture",
	"Automotive",
	"Banking",
	"Beauty & Personal Care",
	"Branding & Creative Agencies",
	"Business Support Services",
	"Climate Tech / CleanTech",
	"Cold Calling",
	"Cold Emailing",
	"Collaboration",
	"Community & Religious Organizations",
	"Competitor Analysis",
	"Construction",
	"Consulting & Advisory",
	"Content Marketing",
	"Conversion Rate Optimization (CRO)",
	"Creativity",
	"CRM Management",
	"Critical Thinking",
	"Cybersecurity",
	"Decision Making",
	"Deal Structuring",
	"Delivery & Couriers",
	"Digital Marketing",
	"Digital Media",
	"Diagnostics & Labs",
	"Ecommerce",
	"Edtech",
	"Email Marketing",
	"Emotional Intelligence",
	"Energy & Utilities",
	"Environmental Services",
	"Events & Entertainment",
	"Fashion & Apparel",
	"Film & TV Production",
	"Fintech",
	"Fitness & Wellness",
	"FMCG",
	"Food & Beverage",
	"Food Services / Restaurants",
	"Funnel Building",
	"Gaming & Animation",
	"Go-To-Market Strategy (GTM)",
	"Growth Experimentation",
	"Growth Loops",
	"Hardware & IoT",
	"Healthtech",
	"Hospitals & Clinics",
	"Hospitality Tech",
	"Hotels & Hospitality",
	"HR & Recruitment Services",
	"HR Tech",
	"HubSpot",
	"Influencer & Creator Economy",
	"Infrastructure Development",
	"Insurtech",
	"Insurance",
	"Internet Service Providers (ISPs)",
	"International Development",
	"Investment & Asset Management",
	"Lead Generation",
	"Leadership",
	"Legal Services",
	"Legaltech",
	"Lifestyle & Consumer Goods",
	"Logistics & Supply Chain",
	"Logistics & Supply Chain Tech",
	"Manufacturing",
	"Martech",
	"Marketing & Advertising Agencies",
	"Media & Entertainment",
	"Mental Health Services",
	"Microfinance",
	"Mining",
	"Mobility & Transport Tech",
	"Negotiation",
	"Nonprofits & NGOs",
	"Objection Handling",
	"Oil & Gas",
	"Online Learning Platforms",
	"Outreach",
	"Paid Ads Management",
	"Partnership Development",
	"Partnership Management",
	"Partnership Negotiation",
	"Pharmaceuticals",
	"Pipedrive",
	"Pitching & Demo Delivery",
	"Private Equity & Venture Capital",
	"Problem Solving",
	"Procurement",
	"Product Positioning",
	"Product-Led Growth (PLG)",
	"Professional Training",
	"Proptech / Real Estate Tech",
	"Proptech Platforms",
	"Proposal Writing",
	"Public Relations",
	"Public Sector",
	"Publishing",
	"Real Estate Development",
	"Relationship Building",
	"Relationship Management",
	"Renewal Management",
	"Reporting & Analytics",
	"Research & Development",
	"Retail & Wholesale",
	"Sales Closing",
	"Sales Forecasting",
	"Sales Process Optimization",
	"Sales Prospecting",
	"Schools",
	"SEO",
	"Skills Development",
	"Social Enterprises",
	"Social Media Management",
	"Software & SaaS",
	"Sports",
	"Stakeholder Management",
	"Strategic Alliances",
	"Telecommunications",
	"Telemedicine",
	"Time Management",
	"Training & Professional Development",
	"Transportation",
	"Universities & Colleges",
	"Upselling",
	"User Acquisition",
	"User Engagement",
	"User Retention Strategy",
	"Value Proposition Design",
	"Vocational Training",
	"Warehousing",
	"Waste & Recycling",
	"Water & Waste Management",
	"Workflow Automation",
	"Zoho CRM",
];
